2013-10-02 12:57:38,542 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/news/views.py", line 24, in index
    context_instance=RequestContext(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: news/index.html
2013-10-02 12:57:38,995 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 12:59:27,655 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/news/views.py", line 24, in index
    context_instance=RequestContext(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 278, in render
    match = condition.eval(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 830, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 578, in resolve
    obj = self.var.resolve(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 728, in resolve
    value = self._resolve_lookup(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 761, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/functional.py", line 204, in inner
    self._setup()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/functional.py", line 270, in _setup
    self._wrapped = self._setupfunc()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 136, in get_user
    user_id = request.session[SESSION_KEY]
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 44, in __getitem__
    return self._session[key]
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 167, in _get_session
    self._session_cache = self.load()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 18, in load
    expire_date__gt=timezone.now()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 398, in get
    num = len(clone)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 106, in __len__
    self._result_cache = list(self.iterator())
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 317, in iterator
    for row in compiler.results_iter():
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 839, in execute_sql
    cursor = self.connection.cursor()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 324, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 182, in _cursor
    self.connection = Database.connect(**conn_params)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  Peer authentication failed for user "gameawards"

2013-10-02 12:59:28,385 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:00:12,833 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/news/views.py", line 24, in index
    context_instance=RequestContext(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 278, in render
    match = condition.eval(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 830, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 578, in resolve
    obj = self.var.resolve(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 728, in resolve
    value = self._resolve_lookup(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 761, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/functional.py", line 204, in inner
    self._setup()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/functional.py", line 270, in _setup
    self._wrapped = self._setupfunc()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 136, in get_user
    user_id = request.session[SESSION_KEY]
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 44, in __getitem__
    return self._session[key]
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 167, in _get_session
    self._session_cache = self.load()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 18, in load
    expire_date__gt=timezone.now()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 398, in get
    num = len(clone)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 106, in __len__
    self._result_cache = list(self.iterator())
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 317, in iterator
    for row in compiler.results_iter():
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 839, in execute_sql
    cursor = self.connection.cursor()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 324, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 182, in _cursor
    self.connection = Database.connect(**conn_params)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  Peer authentication failed for user "gameawards"

2013-10-02 13:00:13,561 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:08:17,337 [ERROR] django.request: Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 219, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    current_app=self.name):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 467, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 311, in app_dict
    self._populate()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 286, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/functional.py", line 31, in wrapper
    result = func(*args)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/runs/views.py", line 9, in <module>
    from gameawards.utils import sanitizeHtml
  File "/home/jorgen/progging/gameawardsDjango/gameawards/utils.py", line 3, in <module>
    from BeautifulSoup import BeautifulSoup, Comment
ImportError: No module named BeautifulSoup
2013-10-02 13:08:17,909 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:08:54,620 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:08:56,489 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:08:59,200 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:24:24,032 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:24:27,874 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:24:37,346 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:24:38,801 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:25:16,164 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:25:17,962 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:25:19,980 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 13:25:22,525 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 15:35:45,399 [ERROR] django.request: Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/content/views.py", line 7, in info_request
    rules = General.objects.get(title='rules')
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: General matching query does not exist.
2013-10-02 15:35:45,691 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 15:39:32,283 [ERROR] django.request: Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/content/views.py", line 9, in info_request
    organizers = General.objects.get(title='organizers')
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: General matching query does not exist.
2013-10-02 15:39:32,510 [WARNING] django.request: Not Found: /favicon.ico
2013-10-02 16:10:07,929 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/news/views.py", line 24, in index
    context_instance=RequestContext(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 102, in render
    compiled_parent = self.get_parent(context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 99, in get_parent
    return get_template(parent)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 186, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
TemplateSyntaxError: 'block' tag with name 'second' appears more than once
2013-10-02 16:10:08,458 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 15:46:39,966 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/news/views.py", line 24, in index
    context_instance=RequestContext(request))
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 156, in render
    len_values = len(values)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "content_slide" does not exist
LINE 1: ..._slide"."text", "content_slide"."belongs_to" FROM "content_s...
                                                             ^

2014-01-19 15:46:40,741 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 16:51:48,981 [ERROR] django.request: Internal Server Error: /games
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/middleware/common.py", line 72, in process_request
    urlresolvers.is_valid_path("%s/" % request.path_info, urlconf)):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/jorgen/progging/gameawards/gameawards/apps/runs/views.py", line 9, in <module>
    from gameawards.utils import sanitizeHtml
  File "/home/jorgen/progging/gameawards/gameawards/utils.py", line 3, in <module>
    from BeautifulSoup import BeautifulSoup, Comment
ImportError: No module named BeautifulSoup
2014-01-19 16:51:49,307 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 16:52:40,035 [ERROR] django.request: Internal Server Error: /games/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/runs/views.py", line 51, in game_list_request
    curr_run = Run.objects.get(current_run = True)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: Run matching query does not exist.
2014-01-19 16:52:40,291 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:08:08,223 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:22:52,488 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:22:54,131 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:22:56,589 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:22:58,279 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:24:31,215 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:32:13,855 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:32:17,624 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:32:19,299 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 17:32:28,130 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 18:29:42,040 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 18:29:44,067 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 18:29:45,644 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 18:30:11,938 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:13,033 [ERROR] django.request: Internal Server Error: /games/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/runs/views.py", line 51, in game_list_request
    curr_run = Run.objects.get(current_run = True)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: Run matching query does not exist.
2014-01-19 21:47:13,321 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:16,610 [ERROR] django.request: Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/content/views.py", line 7, in info_request
    rules = General.objects.get(title='rules')
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: General matching query does not exist.
2014-01-19 21:47:16,783 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:41,006 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:42,786 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:44,433 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:51,571 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:53,554 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:47:59,998 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:01,781 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:09,517 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:12,396 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:16,003 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:26,209 [ERROR] django.request: Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/content/views.py", line 8, in info_request
    categories = General.objects.get(title='categories')
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: General matching query does not exist.
2014-01-19 21:48:26,396 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:35,760 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:38,185 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:40,685 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:48:43,942 [ERROR] django.request: Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/content/views.py", line 9, in info_request
    organizers = General.objects.get(title='organizers')
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: General matching query does not exist.
2014-01-19 21:48:44,120 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:49:04,673 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:49:09,618 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 21:54:44,093 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 22:06:39,721 [ERROR] django.request: Internal Server Error: /profile/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/members/views.py", line 65, in profile_request
    profile = user.get_profile()
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 441, in get_profile
    self._state.db).get(user__id__exact=self.id)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: UserProfile matching query does not exist.
2014-01-19 22:06:40,026 [WARNING] django.request: Not Found: /favicon.ico
2014-01-19 23:25:46,833 [ERROR] django.request: Internal Server Error: /games/
Traceback (most recent call last):
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawards/gameawards/apps/runs/views.py", line 51, in game_list_request
    curr_run = Run.objects.get(current_run = True)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/jorgen/Envs/nga/local/lib/python2.7/site-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: Run matching query does not exist.
2014-01-19 23:25:47,111 [WARNING] django.request: Not Found: /favicon.ico
2014-01-20 09:29:22,619 [WARNING] django.request: Not Found: /favicon.ico
2014-01-20 09:30:55,263 [WARNING] django.request: Not Found: /media/images/admin/nga-2013-winners.png
2014-01-20 09:41:07,873 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jorgen/progging/gameawardsDjango/gameawards/apps/news/views.py", line 24, in index
    context_instance=RequestContext(request))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 149, in get_template
    template = get_template_from_string(template, origin, template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 263, in do_include
    isolated_context=isolated_context)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 146, in __init__
    t = get_template(template_path)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/home/jorgen/.virtualenvs/nga/local/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: templates/news/getstarted.html
2014-01-20 10:32:53,620 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 10:34:14,430 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 10:36:38,144 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 10:59:56,898 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 11:03:57,660 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 12:07:43,344 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /profile/
2014-01-20 12:08:28,994 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /profile/
2014-01-20 12:09:28,338 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /profile/
2014-01-20 12:10:14,324 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /members/edit_member/
2014-01-20 12:10:34,523 [WARNING] django.request: Forbidden (CSRF token missing or incorrect.): /members/edit_member/
2014-01-20 12:34:41,474 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 13:23:29,891 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 13:26:26,005 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
2014-01-20 13:54:27,742 [WARNING] django.request: Not Found: /media/images/admin/NGDC-icon.png
